### ISSUE TITLE
Upgrade Diamond

### ISSUE THREAD

**Issue by semenovroman** [bloomberg/chef-bcpc#1023]
Version of Diamond that we are currently using ( https://github.com/bloomberg/chef-bcpc/blob/7f4ae8e3281f8e59678b510f6c5cb483f8e8fb84/bootstrap/shared/shared_build_bins.sh#L29 ) is leaking memory (and can consume all free RAM) in some situations. 
Issue was reported to Diamond ( https://github.com/python-diamond/Diamond/issues/84 ) and fixed ( https://github.com/python-diamond/Diamond/pull/256 ).
We should upgrade to a version of Diamond that incorporates that fix.

**Comment by erhudy** [comment]
Fixed in #1034.
