### ISSUE TITLE
Upgrade VirtualBox Linux guest additions

### ISSUE THREAD

**Issue by kelvk** [bloomberg/chef-bcpc#1068]
Attempting to use VirtualBox shared folders on a bootstrap node (14.04.3) fails on below error:
`modprobe: ERROR: could not insert 'vboxsf': Unknown symbol in module, or unknown parameter (see dmesg)`

Upgrading VirtualBox Linux guest additions to 5.0.16 fixes it.

**Comment by kamidzi** [comment]
Haven't used this, but it may be useful: https://github.com/dotless-de/vagrant-vbguest
