### ISSUE TITLE
opscode-expander-reindexer not removed

### ISSUE THREAD

**Issue by kelvk** [bloomberg/chef-bcpc#1078]
After upgrading Chef server to 12.6, `opscode-expander-reindexer` keeps attempting to start but fails. This causes monitoring to raise alert when `chef-server-ctl status` returns the down component.

```
run: bookshelf: (pid 55581) 253s; run: log: (pid 51876) 963s
run: nginx: (pid 55653) 252s; run: log: (pid 52131) 961s
run: oc_bifrost: (pid 55689) 252s; run: log: (pid 51682) 967s
run: oc_id: (pid 55755) 251s; run: log: (pid 51686) 966s
run: opscode-erchef: (pid 55823) 251s; run: log: (pid 52013) 962s
run: opscode-expander: (pid 55909) 250s; run: log: (pid 51796) 964s
down: opscode-expander-reindexer: 0s, normally up, want up; run: log: (pid 1596) 1817227s
run: opscode-solr4: (pid 56113) 249s; run: log: (pid 51787) 965s
run: postgresql: (pid 56250) 249s; run: log: (pid 51574) 968s
run: rabbitmq: (pid 56267) 248s; run: log: (pid 51401) 969s
run: redis_lb: (pid 56490) 248s; run: log: (pid 52086) 961s
```

According to https://github.com/chef/chef-server/issues/846 the component is no longer in use, but not cleaned up.

**Comment by kamidzi** [comment]
This is resolved, no?

**Comment by erhudy** [comment]
It gets cleaned up now by the Ansible path. If you upgrade it manually on a local build, you're on your own still. Should we leave it open until it's fixed properly by an upstream Chef Server release?

**Comment by kelvk** [comment]
Leaving this open until Chef Server upstream is fixed or when we get to a major release (maybe 6.0).
