### ISSUE TITLE
New flavor names do not fully display in horizon Instance Launch Flavor Details modal dialog

### ISSUE THREAD

**Issue by kamidzi** [bloomberg/chef-bcpc#1094]
Name field under Launch Instance::Flavor details is truncated and suffixed with ellipsis. Specifically, this is member for element `<table class="flavor_table table-striped">`, under `<fieldset id="launch_instance__setinstancedetailsaction">`

**Comment by erhudy** [comment]
Flavor display looked okay to me in both Kilo and Liberty without truncating any flavor names. What does this look like for you?

**Comment by kamidzi** [comment]
Could not reproduce.
