### ISSUE TITLE
Upgrade hypervisors to trusty (14.04)

### ISSUE THREAD

**Issue by jerenkrantz** [bloomberg/chef-bcpc#116]
We should think about when we want to upgrade from precise/12.04 to trusty/14.04.

One notable change that we know should be fixed in upstream packages captured in 14.04 is #54 where keepalived can drop the VIP under load.  I expect there's more.

Thoughts?

**Comment by erhudy** [comment]
Closing as this work was done as part of 4.0/5.0.
