### ISSUE TITLE
Unify VM and physical machine Cobblering

### ISSUE THREAD

**Issue by cbaenziger** [bloomberg/chef-bcpc#118]
Today, VMs are booted using [enroll_cobbler.sh](https://github.com/bloomberg/chef-bcpc/blob/master/enroll_cobbler.sh), however, bare-metal is booted using [cluster-enroll-cobbler.sh](https://github.com/bloomberg/chef-bcpc/blob/master/cluster-enroll-cobbler.sh). This presents a logical disconnect for new adopters of the project as they mature through the stack being both scripts do largely the same thing.

**Comment by erhudy** [comment]
Closing out as our bootstrap process no longer uses these mechanisms.
