### ISSUE TITLE
openstack token issue not working

### ISSUE THREAD

**Issue by kamidzi** [bloomberg/chef-bcpc#1196]
On mitaka build:

```
$ sudo -i
root@bcpc-vm1:~# ls
adminrc  api_versionsrc  keystonerc
root@bcpc-vm1:~# . adminrc
root@bcpc-vm1:~# openstack token issue
The request you have made requires authentication. (HTTP 401) (Request-ID: req-b0a89350-ce88-4b77-9522-b7d94b488763)
```

**Comment by erhudy** [comment]
I remember encountering an issue with Mitaka where it would not immediately read the Fernet keys. Keystone would wait 10-15 minutes or so and then read the Fernet keys, and then everything would start working. Eventually I stopped being able to reproduce the issue. Maybe that's happening here?

**Comment by kamidzi** [comment]
This may be an issue with migration; Above I had built without setting `bcpc.openstack_release = mitaka`, changed it, then recheffed. I will close for now and reopen if encounter it again during migration testing.
