### ISSUE TITLE
VRRP router_id generation is not robust

### ISSUE THREAD

**Issue by kamidzi** [bloomberg/chef-bcpc#1252]
Edge case - generating VRRP ids on different builds within the same L2 network will lead to collisions. Maybe mapping a UUID to an 8-bit unsigned int would be preferable (collision potential aside).

**Comment by furlongm** [comment]
We could also specify the router_id in the environment?

ie. if the router_id exists in the env file, then don't autogenerate.

**Comment by kamidzi** [comment]
Sounds completely reasonable, though just keep in mind that keepalived is being deprecated for 8.x series.

**Comment by mihalis68** [comment]
I like the idea of supporting the override from the environment file, plus adding a brief note to the documentation mentioning this. I will even take on the latter myself since I wrote the network documentation for this generation of BCPC.
