### ISSUE TITLE
bootstrap_chef.sh fails when VBoxManage is not present

### ISSUE THREAD

**Issue by timfallmk** [bloomberg/chef-bcpc#140]
Although the [boostrap install guide](https://github.com/bloomberg/chef-bcpc/blob/master/bootstrap.md) indicates that bare-metal installations can be bootstrapped using `bootstrap_chef.sh`, this script requires VBoxManage to be present.

**Comment by erhudy** [comment]
Closing as the preferred mechanism is Vagrant now, which won't launch without `VBoxManage` anyway.
