### ISSUE TITLE
Set up ntp orphan mode and manycast

### ISSUE THREAD

**Issue by jerenkrantz** [bloomberg/chef-bcpc#163]
We've discussed this a number of times before - but, I ran into an issue on a recent flight where I needed NTP services but I had restarted VMs and lost NTP sync so the servers wouldn't start.  We should think about two features in NTP land:

- Orphan mode
- manycastserver/manycastclient setup

Manycast would simplify finding the NTP servers:
```
manycastserver 227.221.9.75
manycastclient 227.221.9.75 key 687
```
I believe it just has to be a 'random' multicast address - we can use an auth key or not.  ENOCARE. @trumanboyes may have some tips about what a good address range to use would be.

As for orphan mode, we would have every node in the cluster (except itself) listed as a server - and an appropriately high stratum so it wouldn't interfere with normal services:

```
tos orphan 5
server 10.0.100.12 iburst
server 10.0.100.13 iburst
```

When a node has lost all of its upstreams, all nodes in an orphan mode will 'elect' a leader that will convert itself to stratum 1 / LOOP ID and then all of the other nodes will sync off it.

Looking at the ntp cookbook we are using, it definitely doesn't support this complexity.  So, we'd need to fork the cookbook or roll our own recipes.

For more info:
https://lopsa.org/node/1480
http://www.eecis.udel.edu/~mills/ntp/html/assoc.html
http://www.eecis.udel.edu/~mills/ntp/html/orphan.html

**Comment by erhudy** [comment]
This has been around for nearly 2 years without action so I'm going to tombstone it.
