### ISSUE TITLE
OpenStack VMs occasionally error out on termination due to potential race in nova-network

### ISSUE THREAD

**Issue by jerenkrantz** [bloomberg/chef-bcpc#167]
It looks like nova-network in Havana doesn't always handle a race conditions when multiple VMs are being destroyed on a single hypervisor - it will error out trying to clean up the bridge interfaces.

```
2014-06-19 15:16:02.991 53370 ERROR nova.openstack.common.rpc.common [req-db60b18b-0537-45c1-9189-f76a23e5ffe7 4e22bb03ab08476a92fb01c246e0b77c 6bef6424d20040eca01d63deb1b05be7] Returning exception Unexpected error while running command.
Command: sudo nova-rootwrap /etc/nova/rootwrap.conf dhcp_release br1000 1.127.0.17 fa:16:3e:c5:aa:94
Exit code: 1
Stdout: ''
Stderr: 'cannot setup interface: No such device\n' to caller
```

Issuing another delete command on the VM usually works okay.

(I have not yet looked at whether there is an upstream issue for this.)

**Comment by erhudy** [comment]
I think this is no longer an issue, since my stress testing involved the creation and destruction of large groups of instances (20+) at a time.
