### ISSUE TITLE
non-fatal lint error

### ISSUE THREAD

**Issue by mihalis68** [bloomberg/chef-bcpc#1700]
**Describe the bug**

https://travis-ci.com/github/bloomberg/chef-bcpc/jobs/368244065

**To Reproduce**

**Expected behavior**

**Screenshots**

**Environment (please complete the following information):**
 - Operating System and Version: [e.g. Ubuntu Linux 18.04]
 - Browser [e.g. Firefox, Safari] (if applicable):

**Additional context**

**Comment by comay** [comment]
Closing as this was fixed by Chris as part of the referenced commit.
