### ISSUE TITLE
Cookbook attribute definition inconsistency

### ISSUE THREAD

**Issue by bijugs** [bloomberg/chef-bcpc#176]
Currently we are using strings and symbols to define the keys for node attributes which creates inconsistency and may result in defining the same attribute twice which will become a maintenance challenge. For e.g. the later attributes in "bcpc" cookbook default attribute file is using symbols and the earlier ones  strings which doesn't mean the same. For consistency can we agree on one form which will keep all the code using them consistent as well.

**Comment by erhudy** [comment]
Closing as everything uses strings.
