### ISSUE TITLE
make create-packer-box fails for libvirt

### ISSUE THREAD

**Issue by mihalis68** [bloomberg/chef-bcpc#1811]
**Describe the bug**
If the source box exists, but only for virtualbox, the create packer box step fails because it does not handle vagrant mutating the box

**To Reproduce**

cmorgan@angband:/work/submit$ vagrant box list
bento/ubuntu-18.04 (virtualbox, 202005.21.0)
cmorgan@angband:/work/submit$ make create-packer-box
virtual/packer/bin/create-packer-box.sh
+++ dirname virtual/packer/bin/create-packer-box.sh
++ dirname virtual/packer/bin
+ packer_dir=virtual/packer
+ config_variables=virtual/packer/variables.json
++ jq -r .base_box virtual/packer/variables.json
+ BASE_BOX=bento/ubuntu-18.04
++ jq -r .base_box_version virtual/packer/variables.json
+ BASE_BOX_VERSION=202005.21.0
++ jq -r .output_packer_box_name virtual/packer/variables.json
+ OUTPUT_PACKER_BOX_NAME=bcc-ubuntu-18.04
+ '[' bento/ubuntu-18.04 == null ']'
+ '[' 202005.21.0 == null ']'
+ '[' bcc-ubuntu-18.04 == null ']'
++ vagrant box list --machine-readable
++ grep -i 'bento/ubuntu-18.04.*202005.21.0'
+ base_box_exists='1617550782,,ui,info,bento/ubuntu-18.04 (virtualbox%!(VAGRANT_COMMA) 202005.21.0)'
+ '[' -z '1617550782,,ui,info,bento/ubuntu-18.04 (virtualbox%!(VAGRANT_COMMA) 202005.21.0)' ']'
+ cd virtual/packer
+ command -v packer
+ '[' -d output-vagrant ']'
+ rm -drf output-vagrant
++ packer --version
+ current_packer_ver=1.7.1
+ required_packer_ver=1.4.0
++ printf '%s\n' 1.4.0 1.7.1
++ sort -V
++ head -n1
+ lower_packer_ver=1.4.0
+ '[' 1.4.0 = 1.4.0 ']'
+ VAGRANT_VAGRANTFILE=Vagrantfile
+ packer build --force --var-file=variables.json config.json
vagrant: output will be in this color.

==> vagrant: Creating a Vagrantfile in the build directory...
==> vagrant: Adding box using vagrant box add ...
    vagrant: (this can take some time if we need to download the box)
==> vagrant: Calling Vagrant Up (this can take some time)...
==> vagrant: destroying Vagrant box...
==> vagrant: Deleting output directory...
Build 'vagrant' errored after 5 seconds 504 milliseconds: error: SSH Port was not properly retrieved from SSHConfig.

==> Wait completed after 5 seconds 504 milliseconds

==> Some builds didn't complete successfully and had errors:
--> vagrant: error: SSH Port was not properly retrieved from SSHConfig.

==> Builds finished but no artifacts were created.
make: *** [Makefile:38: create-packer-box] Error 1
cmorgan@angband:~/work/submit$ exit

**Expected behavior**
The script should add the box and then mutate it for libvirt if that is the provider we are using.

**Comment by comay** [comment]
This was resolved by #1812.
