### ISSUE TITLE
Provide Rolling Configuration Updates

### ISSUE THREAD

**Issue by cbaenziger** [bloomberg/chef-bcpc#194]
# Rolling Configuration Restart

To support changing daemon settings and restarting necessary daemons in a controlled fashion while not affecting service availability, we need a way to coordinate service restarts.

I expect that using Zookeeper will provide a lightweight synchronized state system for flagging service availability or outages. Further, for managing daemon restarts on each system one can integrate Chef and Zookeeper using the [Zookeeper Ruby Gem](https://github.com/zk-ruby/zookeeper/) already in use with Chef-BCPC for checking znode existence for [HDFS HA](https://github.com/bloomberg/chef-bcpc/blob/eeaf5d34c29615cd6e53ad47ed94ce12a7f68a1e/cookbooks/bcpc-hadoop/libraries/utils.rb#L158-L164) and [Kafka](https://github.com/bloomberg/chef-bcpc/pull/184/files).

## Eco-System Services Affected
Components which need a rolling restart mechanism of some sort:
  * HDFS
    * Namenodes
    * Datanodes
  * HBase
    * Masters
    * Region Servers
  * Zookeeper
  * MySQL
  * Kafka
  * YARN RM

### Single Active Daemons
A trivial system can be implemented for single active systems like HDFS Namenodes, YARN Resource Managers and . These systems can inform which machine is active and all others can be indiscriminately restarted. As long as we have a backup ready, we can then bounce the active daemon.

These systems will need to be integrated with Chef to understand if we are restarting the active and if so with a backup which has been properly Chef'd already. (Do we want the interlock on only bouncing the active until a backup has been upgraded? This could lead to a update deadlock.)

### Multi Active Daemons
One way to integrate the rolling update in recipes would be for template actions to interact with a ruby_block action for restarting the service (opposed to interfacing with the Chef service action as done today). This way, we can insert logic to schedule a restart conditionally and prevent the daemon restart from causing an outage.

### Positive Flagging
In this approach, our recipes would add a Zookeeper node to flag that an instance of some service is going down for restart and will be offline. This way, unless a service start is considered successful (and we remove the znode) we know that daemon went away.

A challenge is ensure no other daemons are down for other reasons (e.g. hardware failure, network partition, etc.). We can query the overall health of a service to compute the maximal number of nodes which can be permitted dead.

For example, for:
**HDFS Datanode**:
  0. Assumes no under replicated blocks to start with, other than those caused by listed dead datanodes. Assumes `dfs.namenode.stale.datanode.interval` tuned aggressively enough to prevent a hang while restarting.
  1. The namenode can be queried for dead datanodes and and the total number of supported failed daemons computed (e.g. `dfs.replication`-1); this would be the number of available lock znodes
  2. Then Zookeeper can be used to try and create a lock znode (e.g. `/chef-bcpc/rolling_restart/{hdfs_restart_1,hdfs_restart_2}`) with a payload of the machine's hostname and the Chef PID; as this way the recipes can search for any orphans they may have created when running and not needing to create a lock.

**HBase Region Server**:
  0. Assumes `hbase.balancer.period` is longer than a Region Server's restart time
  1. Only [HBASE-10070](https://issues.apache.org/jira/browse/HBASE-10070) tables will be coordinated -- as migration of non-replicated regions is a much too slow process on which to gate configuration updates
  2. Chef queries HBase to determine minimum replication count for all replicated tables. That many locks are created and the process runs as for HDFS step 2

### Negative Flagging

In this approach, our machines would run a daemon to hold an ephemeral znode stating that a server is alive (perhaps running local canary checks on the server as well). These znodes could be verified against Chef reported total number of nodes for a particular service to determine the acceptable loss quantity.

This system provides for a uniform process to check quantity of available daemons but starts to muddy the layers of monitoring, daemon specific metrics, service specific HA logic, etc. 

A failure in this approach means we errantly believe a service to be alive which is not.

## Methods for Preventing Outage

If we detect the cluster can not tolerate another daemon exiting of the type needing update, then we need to determine the action to take.

Some actions:
  1. We can simply **poll & wait** for a slot to open allowing us to restart
    * Effectively hanging the Chef run should all slots be consumed for a long time
    * Ensures if Chef runs through successfully across the cluster that all machines should be consistent; but may back-up multiple Chef runs if the propagation takes longer than the Chef-Client automatic run interval
  2. We can **fail the Chef run should no slots be open for restarting**
    * To support the cluster eventually converging need to implement a way to leave a bread-crumb that the service needs a restart
      * Could be check mtime of notifying files/templates/configs. and start time of daemon if start time is older then bounce
    * Effectively denial-of-service's any updates Chef actions after the out-of-sync daemon
    * Ensures if Chef runs through successfully across the cluster that all machines should be consistent
  3. We can **skip restarting the daemon restart if all slots full**
    * Like 2: to support the cluster eventually converging need to implement a way to leave a bread-crumb that the service needs a restart
        * Could still be check mtime of notifying files/templates/configs. and start time of daemon if start time is older then bounce
    * Requires staged deployments of multi-daemon configuration changes; e.g. if we need to update HDFS & HBase:
           1. Deploy HDFS change
           2. Ensure all nodes updated
           3. Deploy HBase change
           4. Ensure all nodes updated
    * Requires some out-of-band way to determine cluster-wide upgrade status; successful completion of Chef runs is not indicative of an in-sync cluster

# Future Directions & Thoughts

## Toxic Configuration Prevention
To enable safer cluster configuration updates, we can prevent configuration updates from being acted upon by creating a too-many-errors flag for administratively prohibiting daemon restarts should too many workers fail -- this way, should a toxic configuration be pushed and the daemon fail its start up criteria we can prohibit more machines following.

## Weightiness

Are these proposals too heavy weight or invasive? Can we leverage the eco-system component more for restart gating than having to flog Zookeeper?

**Comment by erhudy** [comment]
Closing as Hadoop-specific.
