### ISSUE TITLE
Instance snapshots saving to local disk

### ISSUE THREAD

**Issue by jerenkrantz** [bloomberg/chef-bcpc#249]
When issuing an instance snapshot on master (Icehouse), I caught `nova-compute` executing `qemu-img`:

```
root@bcpc-vm1:/var/log/cinder# ps -ef | grep qemu
nova     47866 36854 91 22:02 ?        00:00:08 qemu-img convert -O raw rbd:images/f99496b9-9a8b-416c-b9eb-3f03c8a06ad1_disk:id=admin:conf=/etc/ceph/ceph.conf /var/lib/nova/instances/snapshots/tmpxqQo8X/b4e014ac71fc472393b7166349940a15
```

(36854 is nova-compute - very curious why it's not cinder.)

This is ungood - I'll use this issue to log any investigations.

**Comment by erhudy** [comment]
Closing as we no longer allow instance snapshots as a matter of policy to general tenants (and I believe that when we test it as admins, they stay in Ceph as expected).
