### ISSUE TITLE
Ceph can't replicate correctly when cluster is configured to use only SSDs

### ISSUE THREAD

**Issue by sudssm** [bloomberg/chef-bcpc#262]
If, in the cluster configuration file, one specifies only SSDs (and no HDDs), it is not possible to correctly chef a node. In particular, ceph gets stuck because it is unable to replicate across multiple racks/disk types.

This should either be documented somewhere or fixed.

Cluster configuration that breaks:

      "ceph": {
        "pgp_auto_adjust" : false,
        "hdd_disks" : [  ],
        "ssd_disks" : [ "sdb", "sdc", "sdd", "sde", "sdf", "sdg" ],
        "chooseleaf" : "host"
      },

And a fix for it

      "ceph": {
        "pgp_auto_adjust" : false,
        "hdd_disks" : [ "sdb", "sdc", "sdd" ],
        "ssd_disks" : [ "sde", "sdf", "sdg" ],
        "chooseleaf" : "host"
      },

**Comment by erhudy** [comment]
This is a very old issue, but I can confirm that it functions properly now by specifying `hdd`/`ssd` under `['bcpc']['ceph']['default']['type']`.
