### ISSUE TITLE
Make setting up disks a dynamic process

### ISSUE THREAD

**Issue by amithkanand** [bloomberg/chef-bcpc#277]
Current `bcpc-hadoop::disk` recipe uses disks defined in the environment file. In case of a disk failure, failed disk is not detected by the recipe and hence hadoop configuration files are not updated while the disk replacement is in progress. The recipe should be changed to fetch disks dynamically from the system (using OHAI or some other utility) to get correct picture of disks in the system.

**Comment by erhudy** [comment]
Closing as Hadoop-specific.
