### ISSUE TITLE
Glance cache not configured correctly 

### ISSUE THREAD

**Issue by caiush** [bloomberg/chef-bcpc#289]
Think this is bug. We are not pruning the glance image cache anywhere so it just grows in size slowly. 

Glance provides a bunch of tools to manage this cache, but generally the auth doesn't work for them. 

There is a pretty good docs page on glance-cache: 
http://docs.openstack.org/developer/glance/cache.html

We need a cron job (or better) to do cleanup like this.

**Comment by erhudy** [comment]
We no longer use Glance caching because images remain in RBD at all times (running `glance-cache-manage` will also reply that the cache management middleware is not enabled).
