### ISSUE TITLE
Dynamically compute values for parameters

### ISSUE THREAD

**Issue by amithkanand** [bloomberg/chef-bcpc#298]
In current implementation, all memory related and disk related parameters are hard coded into template/environment files. It makes it little challanging when using the same code base to setup clusters on multiple environments that have completely different hardware configurations. We should be able to query Ohai data to determine hardware configuration and based on that the parameters can be calculated during cluster build process.

**Comment by erhudy** [comment]
Closing as Hadoop-specific.
