### ISSUE TITLE
Networking is restarted needlessly

### ISSUE THREAD

**Issue by cbaenziger** [bloomberg/chef-bcpc#303]
Due to the `sysctl_param` LWRP notifying that we updated repeatedly it seems we needlessly restart [networking](https://github.com/bloomberg/chef-bcpc/blob/3542dd6a6d017bcb6d1dac8b851b3a484acb8088/cookbooks/bcpc-hadoop/recipes/configs.rb#L7-9) every Chef run. This is not helped by us [freezing](https://github.com/bloomberg/chef-bcpc/blob/2aa074ad2d011ded2c4f2c796df6e2fe8381b84d/setup_chef_cookbooks.sh#L58) the `sysctl` cookbook at version 0.3.5; there is an idempotency PR [onehealth-cookbooks/sysctl#3](https://github.com/onehealth-cookbooks/sysctl/pull/3) which I suspect will help too.

**Comment by erhudy** [comment]
Closing as Hadoop-specific.
