### ISSUE TITLE
Update get_mysql_nodes to use get_nodes_for

### ISSUE THREAD

**Issue by cbaenziger** [bloomberg/chef-bcpc#307]
To remove the old assumption that the first machine to call [`get_mysql_nodes()`](https://github.com/bloomberg/chef-bcpc/blob/f5a0fa2cdd3906f6a041580c5e7d38da47455920/cookbooks/bcpc/libraries/utils.rb#L118-122) is a MySQL host, we should update to using `get_nodes_for()` to determine the correct MySQL host(s).

**Comment by erhudy** [comment]
Closing as Hadoop bug.
