### ISSUE TITLE
Improvement: Use attributes for port numbers

### ISSUE THREAD

**Issue by bijugs** [bloomberg/chef-bcpc#309]
We have port numbers hardcoded in many code components and they need to be modified to use attributes so that the port numbers can be changed seamlessly. Following are some of the locations where hardcoded port number are used.

cookbooks/bcpc-hadoop/templates/default/hdp_hdfs-site_HA.xml.erb
cookbooks/bcpc-hadoop/templates/default/hdp_yarn-site.xml.erb
cookbooks/bcpc-hadoop/templates/default/hue_hue.ini.erb
cookbooks/bcpc-hadoop/templates/default/hb_hbase-site.xml.erb
cookbooks/kafka-bcpc/recipes/kafka.rb

The plan is to modify them as we implement the rolling restart for various components.

**Comment by erhudy** [comment]
Closing as Hadoop-specific.
