### ISSUE TITLE
Improvement: Remove duplicate library functions

### ISSUE THREAD

**Issue by bijugs** [bloomberg/chef-bcpc#310]
Currently we have duplicate library functions under BCPC and BCPC-Hadoop cookbook. For e.g. [get_nodes_for](https://github.com/bloomberg/chef-bcpc/blob/hadoop_hortonworks/cookbooks/bcpc-hadoop/libraries/utils.rb#L123-L130) function and there are others as well. We need to consolidate them into one location so that code changes doesn't have to be made at multiple locations.

**Comment by erhudy** [comment]
Closing as Hadoop-specific.
