### ISSUE TITLE
Cleanup Recipes for multiple components

### ISSUE THREAD

**Issue by amithkanand** [bloomberg/chef-bcpc#313]
We have split recipes for each component into two parts i.e. configuration recipe and installation recipe. After splitting, the functionality is working as expected and now it is time to further clean the recipes. For example for setting up only a data node [`yarn-site.xml`](https://github.com/bloomberg/chef-bcpc/blob/hadoop_hortonworks/cookbooks/bcpc-hadoop/recipes/hadoop_config.rb#L27-27) is not needed and it should be moved under nodemanager recipe. Similarly a [`hadoop-client`](https://github.com/bloomberg/chef-bcpc/blob/hadoop_hortonworks/cookbooks/bcpc-hadoop/recipes/datanode.rb#L6-6) is not needed on a server node. The second round of clean up will further enhance the management and installation on each component.

**Comment by erhudy** [comment]
Closing as Hadoop-specific.
