### ISSUE TITLE
Enhancement: Avoid using global and instance variables in library functions

### ISSUE THREAD

**Issue by bijugs** [bloomberg/chef-bcpc#322]
By using non local variables in library functions, we are exposing variables to other functions to change it. Currently we have few instances e.g. [init_config](https://github.com/bloomberg/chef-bcpc/blob/4c4ba33f0106468f287470e29e624be3b163326c/cookbooks/bcpc-hadoop/libraries/utils.rb#L32), [znode_exists](https://github.com/bloomberg/chef-bcpc/blob/4c4ba33f0106468f287470e29e624be3b163326c/cookbooks/bcpc-hadoop/libraries/utils.rb#L166). As a standard we should be using only local variables in all the library functions.

init_config is a special case since it caches the Chef data bag values and other functions need to access the cache to get and set values. Caching is primarily to avoid calls to Chef server. Data access restriction in this case can be implemented by creating a Class so that all the related functions are in the class and only these functions will be able to access the variables which stores Chef data bag values. Following is a sample library Class definition and how it can be used in recipes.

**In the library file:**
```
class Chef::Recipe::BCPCCONFIGS

  def self.init_config
     @node_passwd = "This is from test-chef-class"
  end

  def self.get_config
     @node_passwd
  end

  def self.set_config(new_config_val)
     @node_passwd = new_config_val
  end
end
```
**In the recipe:**
```
ruby_block "test-chef-class" do
  block do
    BCPCCONFIGS.init_config
    BCPCCONFIGS.set_config("Change config value")
  end
end

ruby_block "Check-chef-class" do
  block do
    passwd =  BCPCCONFIGS.get_config
  end
end
```

**Comment by erhudy** [comment]
Closing as Hadoop-specific.
