### ISSUE TITLE
Enhancement: Create library namespaces to avoid name collisions

### ISSUE THREAD

**Issue by bijugs** [bloomberg/chef-bcpc#323]
Currently we are not using library namespaces which will create name collisions between cookbook library methods. We should create [namespaces](http://www.getchef.com/blog/2014/03/12/writing-libraries-in-chef-cookbooks/) for our cookbook libraries to avoid this issue since we will not have control over community cookbooks.  Since we are keeping BCPC and BCPC-Hadoop common library methods in sync manually we may not have an issue now.

**Comment by erhudy** [comment]
Closing as Hadoop bug.
