### ISSUE TITLE
Abort cluster creation if any of the downloads in the vbox_create fails

### ISSUE THREAD

**Issue by bijugs** [bloomberg/chef-bcpc#324]
If any of download process in the [software download step](https://github.com/bijugs/chef-bcpc/blob/4f0cb509c12f69c8b3cb6657ba7b3f367e4ab48d/vbox_create.sh#L39-L61) in vbox_create script fails, the cluster creation process need to be aborted since these software components are required. Currently the connection to download the PXE boot rom fails, but the cluster creation process continues and loops indefinitely for the  VMs to come-up which will never happen !!

**Comment by erhudy** [comment]
Closing as this bootstrap mechanism is being deprecated.
