### ISSUE TITLE
cluster-assign-roles.sh should save run_list and node object

### ISSUE THREAD

**Issue by cbaenziger** [bloomberg/chef-bcpc#329]
We should not be using the `-o` option to `chef-client` as it is not designed to save the `run_list` or the `node` object back which cluster-assign-roles is explicitly trying to do. As such we should pull `-o` from: [cluster-assign-roles.sh](https://github.com/bloomberg/chef-bcpc/blob/e407c0c24d3e1afa7dc7854a41ceffd7e6ea444c/cluster-assign-roles.sh#L47).

**Comment by erhudy** [comment]
Closing as we do not do this.
