### ISSUE TITLE
Enhancement: Decouple the test cluster creation components and process

### ISSUE THREAD

**Issue by bijugs** [bloomberg/chef-bcpc#334]
**Motivation:** Users of Chef-BCPC should be able to create clusters to their specification. Some examples being

- Be able to bring up a test cluster with only HDFS and HBASE or
- Be able to being up a test cluster with only OS/Base software on them so that it can be used to install say Cassandra or
- Be able to bring up a 6 node test cluster

Currently test clusters are created based on certain assumptions like 3 node cluster and is tightly coupled. For e.g. the datanode.rb recipe installs a set of software which may not be required in a test environment.
By decoupling the process and components the code can be used to create test clusters of various configurations and code can be maintained efficiently. This will also help in the adoption of Chef-BCPC to create test environments widely in the community.

**Comment by erhudy** [comment]
Closing as Hadoop bug.
