### ISSUE TITLE
Netlink errors in keepalived

### ISSUE THREAD

**Issue by pchandra** [bloomberg/chef-bcpc#34]
When bringing up a headnode, keepalived is happy (the `VRRP_Script` lines below) and then 2-3 minutes later, it logs some `Netlink: filter function error` messages. This happens reliably for me when I'm testing in VMs, so I think it's an issue. Googling around says that once you see them, you should restart keepalived to make sure it's still working properly. In testing, once I restart keepalived, those messages don't pop back up (I waited 30+ mins and didn't see anything).

```
Aug 18 11:41:02 bcpc-vm2 Keepalived_vrrp: VRRP_Script(chk_haproxy) succeeded
Aug 18 11:41:02 bcpc-vm2 Keepalived_vrrp: VRRP_Script(chk_ceph) succeeded
Aug 18 11:42:55 bcpc-vm2 Keepalived_vrrp: Netlink: filter function error
Aug 18 11:42:55 bcpc-vm2 Keepalived_healthcheckers: Netlink: filter function error
Aug 18 11:42:56 bcpc-vm2 Keepalived_healthcheckers: Netlink: filter function error
Aug 18 11:42:56 bcpc-vm2 Keepalived_vrrp: Netlink: filter function error
Aug 18 11:43:14 bcpc-vm2 Keepalived_vrrp: Netlink: filter function error
Aug 18 11:43:14 bcpc-vm2 Keepalived_healthcheckers: Netlink: filter function error
Aug 18 11:43:14 bcpc-vm2 Keepalived_healthcheckers: Netlink: filter function error
Aug 18 11:43:14 bcpc-vm2 Keepalived_vrrp: Netlink: filter function error
```

**Comment by camelcamro** [comment]
getting it as well - allmost all the time.
can this not be fixed ?

**Comment by guillaumefenollar** [comment]
Happening a lot here too. I have several virtual routers with basic configurations and all are having this behavior. Cannot prove it’s doing anything wrong though.

**Comment by mihalis68** [comment]
Not against re-opening this if it causes an issue. Some questions: is this happening in real clusters (on metal) or just in virtualbox? Is it happening in the case where you have > 1 head node, so there's real high availability functionality going on (e.g. VIP could jump)?

**Comment by guillaumefenollar** [comment]
I confirm it’s happening on 5 different clusters in my infrastructure, where HA is working properly when needed.

**Comment by kamidzi** [comment]
Isn't this a keepalived issue, not necessarily chef-bcpc?

**Comment by mihalis68** [comment]
we may need to select keepalived more mindfully than just getting it from ubuntu
