### ISSUE TITLE
Enhancement: Improve chef run performance by saving only the required attributes to server

### ISSUE THREAD

**Issue by bijugs** [bloomberg/chef-bcpc#350]
We should be able to use [whitelist-node-attrs](https://github.com/opscode-cookbooks/whitelist-node-attrs) cookbook and control the data which need to be stored back to the server during chef client runs. Only attributes we would need across chef client runs are that will be used to determine the state from the past run like whether a service restart failed or not. By minimizing the amount of data saved the performance of Chef client runs and also the Chef server will be better. See this [presentation](https://www.socallinuxexpo.org/sites/default/files/presentations/cfgmgmt.pdf) slides from FB starting slide number 20 on the node.save issue.

**Comment by erhudy** [comment]
Closing as Hadoop bug.
