### ISSUE TITLE
Migrate all the scripts in the repo root to a subdir

### ISSUE THREAD

**Issue by pchandra** [bloomberg/chef-bcpc#36]
Just opening a placeholder for anyone feeling motivated to move the automation scripts to a subdir, since it's getting crowded IMHO. It'll take a little bit of review and testing since some may need a little re-writing to accommodate relative dirs, other assumptions, etc.

**Comment by erhudy** [comment]
Assigned to @mihalis68 to move the cluster tools to a subdirectory.
