### ISSUE TITLE
Service[pdns] restart hangs

### ISSUE THREAD

**Issue by ghost** [bloomberg/chef-bcpc#368]
10.0.100.11 [2014-10-28T10:23:26+00:00] INFO: Processing service[pdns] action restart (bcpc::powerdns line 420)

The knife bootstrap process has hung a few times at this point. I've let it run for up to 40 minutes. 10.0.100.11 doesn't seem to be heavily loaded. I've tried restarting it which had no effect.

On 10.0.100.11, I've tried "/usr/bin/pdns_control list" which also hangs at this call:

    connect(3, {sa_family=AF_FILE, path="/var/run/pdns.controlsocket"}, 110

I'll continue investigating.

**Comment by erhudy** [comment]
PowerDNS is at 3.3 in Trusty and nobody has reported this problem since then, so closing.
