### ISSUE TITLE
Define your flavor 

### ISSUE THREAD

**Issue by caiush** [bloomberg/chef-bcpc#378]
Rather than taking the default flavors from upstream allow the user to define their flavors in configuration. This should be overrideable in the environment. 

e.g. 
```
bcpc_os_flavor "m1.tiny" do
    vcpu 1
    disk_gb  0
    ram_mb 1024
    [id  4] #optional id
end 
```
Then define a list of flavors in the environment file.

**Comment by erhudy** [comment]
This is now part of the codebase via #700.
