### ISSUE TITLE
updates to cobbler-managed dhcpd template are not propagating to DHCP server

### ISSUE THREAD

**Issue by kamidzi** [bloomberg/chef-bcpc#379]
Any updates to /etc/cobbler/dhcp.template will not propagate to the dhcpd  configuration file at /etc/dhcp/dhcpd.conf. The current cobbler recipe will restart cobblerd (see https://github.com/bloomberg/chef-bcpc/blob/master/cookbooks/bcpc/recipes/cobbler.rb#L57 ), but that doesn't appear to be sufficient. See: http://www.cobblerd.org/manuals/2.6.0/3/2/2_-_Sync.html and http://www.cobblerd.org/manuals/2.6.0/3/4/1_-_Managing_DHCP.html

**Comment by erhudy** [comment]
This is now fixed by #915, which adds a resource to invoke `cobbler sync` on changes to the template.
