### ISSUE TITLE
Make image-uploading permissions configurable 

### ISSUE THREAD

**Issue by caiush** [bloomberg/chef-bcpc#388]
There is much debate about if the glance (and other) policy documents are configuration. Regardless of that, we need a way to switch off some functionality depending on the use case of the cluster. 

For example, glance uploads currently put a lot of load on the Head nodes. In some clusters people may not wish to even allow custom images. Thus we should provide a turn it off in the environment file. 

This should be pretty easy to do, just template the glance policy file and make `image-upload` an admin only operation if `node['bcpc']['glance']['policy']['image-upload']="admin"` (for example).

**Comment by erhudy** [comment]
This is now done (or will shortly be) with @semenovroman's work on policy.
