### ISSUE TITLE
get_head_nodes util function is too specific 

### ISSUE THREAD

**Issue by caiush** [bloomberg/chef-bcpc#413]
Parts of our recipes reap things based on lists returned from chef-server. For example, 

```
ruby_block "reap-dead-ceph-mon-servers" do
    block do
        head_names = get_head_nodes.collect { |x| x['hostname'] }
        status = JSON.parse(%x[ceph --admin-daemon /var/run/ceph/ceph-mon.#{node['hostname']}.asok mon_status])
        status['monmap']['mons'].collect { |x| x['name'] }.each do |server|
            if not head_names.include?(server)
                %x[ ceph mon remove #{server} ]
            end
        end
    end
end
```

The `get_head_nodes` function searches for matches to `role:BCPC-Headnode`. There are often cases when you need to modify the head node role because, for example, you want to change the disk layout for this server. A reasonable way to do this would be to create a new role e.g. `BCPC-Headnode-VendorX` and include the `BCPC-Headnode` role in its run list. 

However, this causes the node to reap itself! 

I suggest that rather than look for `role:BCPC-Headnode` we actually look for the feature we are trying to match, in this case a node that has the recipe `ceph-head` in its run list. 

Longer term we might want to consider some fancy zookeeper (or whatever) service discovery.

**Comment by kamidzi** [comment]
Could we just proceed using the @kkoh61's `search_nodes()` interface?
