### ISSUE TITLE
vm-to-cluster.sh broken by kernel 3.13

### ISSUE THREAD

**Issue by mihalis68** [bloomberg/chef-bcpc#420]
Upon merging PR https://github.com/bloomberg/chef-bcpc/pull/419 into my local code I discovered my own workflow no longer works. I use vm-to-cluster.sh to get the IP addresses from VirtualBox after the VMs boot and insert them into cluster.txt for use with cluster-assign-roles.sh. It is not necessary to use this for building a typical VM cluster, however this issue ticket is to record the issue for investigation. May need a newer VirtualBox or adjusted parameters being passed to it when the VMs are created. Assigning to myself.

**Comment by erhudy** [comment]
Closing this issue because it pertains to an obsolete version of BCPC.

**Comment by mihalis68** [comment]
I think I fixed that anyway. Will check when I'm next on a suitable computer 

Sent from Rivendell

----- Original Message -----
From: Edmund Rhudy <reply@reply.github.com>
To: chef-bcpc@noreply.github.com
CC: CHRIS MORGAN
At: 25-Aug-2015 09:08:00


Closing this issue because it pertains to an obsolete version of BCPC.
