### ISSUE TITLE
Switch to using iPXE

### ISSUE THREAD

**Issue by kamidzi** [bloomberg/chef-bcpc#432]
iPXE is so very much nicer than PXELINUX. 

http://ipxe.org/

**Comment by erhudy** [comment]
iPXE claims comprehensive UEFI support now (http://ipxe.org/efi/vision), and since we are interested in simulating UEFI boot and getting away from legacy BIOS, it's likely worth our time to revisit this soon.

**Comment by erhudy** [comment]
I looked into this very briefly - VirtualBox has a cap of 56KB for ROMs and will silently fail to load ROMs larger than this. The iPXE ROM generated by rom-o-matic.eu was 63KB in size. Additionally, you cannot provide ROMs of any type if the VM is in EFI mode, as VirtualBox will fail to start and confusingly complain about not being able to read RamSize. Unsetting the extra data path to the ROM resolves that error, but then you can't load a ROM.
