### ISSUE TITLE
Auto-restart nova-api on failure detection

### ISSUE THREAD

**Issue by kelvk** [bloomberg/chef-bcpc#437]
nova-api should be in scope for auto-restart (https://github.com/bloomberg/chef-bcpc/pull/405).

**Comment by caiush** [comment]
sadly nova-api doesn't heartbeat the database, so thats why it doesn't get at restarted. However, the api does listen on `169.254.169.254:8775`, so we need to monitor that on the local host. 
```
ubuntu@bcpc-vm1:~$ curl -v  169.254.169.254:8775
* About to connect() to 169.254.169.254 port 8775 (#0)
*   Trying 169.254.169.254... connected
> GET / HTTP/1.1
> User-Agent: curl/7.22.0 (x86_64-pc-linux-gnu) libcurl/7.22.0 OpenSSL/1.0.1 zlib/1.2.3.4 libidn/1.23 librtmp/2.3
> Host: 169.254.169.254:8775
> Accept: */*
>
< HTTP/1.1 200 OK
< Content-Type: text/html; charset=UTF-8
< Content-Length: 98
< Date: Fri, 09 Jan 2015 04:57:52 GMT
<
```

**Comment by erhudy** [comment]
Auto-restart was removed for Kilo, as services actually stay running without falling over these days. Progress!
