### ISSUE TITLE
fpm creates wrong version of python-requests-aws; breaks bootstrap

### ISSUE THREAD

**Issue by jmacarthur** [bloomberg/chef-bcpc#457]
For some reason the call to fpm in cookbooks/bcpc/files/default/build_bins.sh makes python-requests-aws_0.1.6.deb out of the 0.1.5 tarball. See paste below:

http://pastebin.com/HNy82Rxx

This is breaking BCPC-Headnode bootstrap. I'll keep investigating.

**Comment by jmacarthur** [comment]
Looks like fpm ignores the downloaded code and just downloads the latest version of requests-aws.

**Comment by jmacarthur** [comment]
Passing -v 0.1.5 to fpm and removing the explicit download seems to do the same thing (it downloads from the same place). Testing a patch now.

**Comment by kamidzi** [comment]
Thanks! Please reference the issue in the commit message next time to close this automatically.
