### ISSUE TITLE
ceph upgrade process is dangerous 

### ISSUE THREAD

**Issue by caiush** [bloomberg/chef-bcpc#482]
The ceph-common cookbook does an apt-get upgrade on ceph. There are multiple problems here:
1. If  there is a new major version is available then this will roll it out x the cluster at random. Which is bad.
2. A minor upgrade won't result in a restart of the services that need to get hup-ed 
3. It doesn't actually upgrade all the right packages.

This is just plain dangerous. 

I propose we do this process out of chef in orchestration tool, probably as part of a wider apt-get upgrade process.

**Comment by erhudy** [comment]
This was fixed with the 5.0.0 release, where all Ceph package versions are pinned now.
