### ISSUE TITLE
Introduced dependency on keystone in ceph recipe breaks build.

### ISSUE THREAD

**Issue by kamidzi** [bloomberg/chef-bcpc#496]
The keystone sections introduced in #484 are triggering a data access timing condition. Specifically:

```


    ================================================================================
    Error executing action `create` on resource 'template[/etc/ceph/ceph.conf]'
    ================================================================================

    Chef::Mixin::Template::TemplateError
    ------------------------------------
    No config found for get_config(keystone-admin-token)!!!

    Resource Declaration:
    ---------------------
    # In /var/chef/cache/cookbooks/bcpc/recipes/ceph-common.rb

```

**Comment by kamidzi** [comment]
Maybe a short-term fix would be to run all the `make_config` calls in the first runlist item?

**Comment by mihalis68** [comment]
Is this a race condition then? I'm confused about how it would work for me and fail for you, but if it's a race condition that I get.

**Comment by kamidzi** [comment]
I don't believe its a race. I've experienced this on 5 separate builds.

**Comment by mihalis68** [comment]
Does it work after you chef a few times?

**Comment by mihalis68** [comment]
Oh, ok now I remember, I think i chefed this change into an existing VM cluster after merging a trivial previous PR. So that's totally my mistake, sorry!

**Comment by mihalis68** [comment]
Fixed by above-mentioned PR, which I just merged.
