### ISSUE TITLE
Enable auto refresh of quotas

### ISSUE THREAD

**Issue by caiush** [bloomberg/chef-bcpc#505]
From a recent spec:
https://review.openstack.org/#/c/161782/2/specs/liberty/refresh-quotas-usage.rst

We can enable some  degree of auto refreshing of quotas by:
```
* until_refresh (IntOpt) Count of reservations until usage is refreshed	81
* max_age       (IntOpt) Number of seconds between subsequent usage refreshes	82
```
This wont always work but its probably worth having it on.

**Comment by erhudy** [comment]
This was fixed by #749.
