### ISSUE TITLE
Reset min_size to 2

### ISSUE THREAD

**Issue by caiush** [bloomberg/chef-bcpc#512]
Talking to the ceph guys they recommend that we run a min_size of 2. Currently, we end up with a min_size of one because we build clusters starting with one node. This sets the "size" of a cluster to 1, thus ceph (quite rightly) assumes you probably want a min size of 1. The problem is we never come back and fix this.

**Comment by kamidzi** [comment]
What is the severity of this?

**Comment by kelvk** [comment]
Should this be applied to all pools?

**Comment by caiush** [comment]
yes, all pools I think... better late than never!
