### ISSUE TITLE
Enable RBD cache on libvirt 

### ISSUE THREAD

**Issue by caiush** [bloomberg/chef-bcpc#514]
In firefly this is off by default.

**Comment by caiush** [comment]
here is the docs for firefly:http://ceph.com/docs/v0.80.5/rbd/rbd-config-ref/

**Comment by kelvk** [comment]
I found the following statement in the docs important, and probably something tenants should know about.

"Since the cache is local to the client, there’s no coherency if there are others accessing the image. Running GFS or OCFS on top of RBD will not work with caching enabled."

**Comment by kelvk** [comment]
Fixed in #653
