### ISSUE TITLE
Switch DHCP server to dnsmasq

### ISSUE THREAD

**Issue by kamidzi** [bloomberg/chef-bcpc#515]
This is for easier management during the bootstrap procedure. Using dnsmasq should allow simple local dns resolution. It remains to be seen whether TFTP should remain served by a separate daemon.

**Comment by cbaenziger** [comment]
Kundai, do you have any pointers of the advantages of dnsmasq over ISC dhcpd?

**Comment by kamidzi** [comment]
I find it simpler and it integrates a dns; or rather is a dns server that integrates a dhcp server. It would be useful for hosts that receive dhcp leases to be available in dns so we could stop hard-coding IPs during build.

**Comment by kamidzi** [comment]
I find it simpler and it integrates a dns; or rather is a dns server that integrates a dhcp server. It would be useful for hosts that receive dhcp leases to be available in dns so we could stop hard-coding IPs during build.

**Comment by kamidzi** [comment]
I find it simpler and it integrates a dns; or rather is a dns server that integrates a dhcp server. It would be useful for hosts that receive dhcp leases to be available in dns so we could stop hard-coding IPs during build.
