### ISSUE TITLE
Restored VirtualBox VMs from snapshot suffer from clock drift

### ISSUE THREAD

**Issue by kamidzi** [bloomberg/chef-bcpc#517]
This will kill chef runs will something like:

```
10.0.100.12 ================================================================================
10.0.100.12 Chef encountered an error attempting to create the client "bcpc-vm2.local.lan"
10.0.100.12 ================================================================================
10.0.100.12
10.0.100.12 Authentication Error:
10.0.100.12 ---------------------
10.0.100.12 Failed to authenticate to the chef server (http 401).
10.0.100.12 The request failed because your clock has drifted by more than 15 minutes.
10.0.100.12 Syncing your clock to an NTP Time source should resolve the issue.
```

`ntpdate` refuses to work:

```
# ntpdate
12 Mar 16:10:32 ntpdate[1482]: no servers can be used, exiting
```

**Comment by jerenkrantz** [comment]
This is perhaps because ntpd is already running.  You can run 'hwclock -s'
to resync.  I do not think that there is anything we can (or should) do.

**Comment by mihalis68** [comment]
I don't have a fix, but in case the following is of any help, I'll mention that you can force this to work again and indeed I do that in the chefit.sh script (called from cluster-assign-roles.sh script), it looks like this 

```
GOODDATE=`date`
$SSHCMD "date -s '$GOODDATE'" sudo
```

Very crude, but acceptable considering that once the time is within bounds chef can run and it will install ntp which will set the time more reliably without the above ugliness.

**Comment by kamidzi** [comment]
@mihalis68, that's what I have been doing (begrudgingly). @jerenkrantz - I like that suggest. Actually, it has just occurred to me that that output is from a machine that was snapshotted before ntp is configured.. o_O

**Comment by jerenkrantz** [comment]
I also see something similar with VMware Fusion.  Even `hwclock` didn't help (as it too had the wrong time) - however, what helped significantly was installing `open-vm-tools`.  I don't know if that will help with VirtualBox, but it does with VMware.  (I may submit a PR to optionally install open-vm-tools on the hypervisor - TBD.)

**Comment by erhudy** [comment]
When confronted with a VM with wildly inaccurate time, I hit it with `ntpdate -u X.X.X.X` to sledgehammer the clock back to where it's supposed to be.

**Comment by jerenkrantz** [comment]
Yah, the problem is that `ntpdate` doesn't work if you don't have an internet connection (e.g., at 35,000ft which is when I always seem to hit this).

I had some patches a while back to have the bootstrap server run a fallback NTP stratum.  Perhaps the headnodes/VIP should run it - the key thing is that they should all be out-of-sync together.  Chaos ensues when they are all out of sync.

For my purposes, it may be more useful to have it off bootstrap server as Chef screams loudly in this case; but, Ceph will also complain if the mons are out of sync.

**Comment by mihalis68** [comment]
Headnodes/vip feels right to me. It feels wrong to wire the bootstrap and/or chef server any more tightly into the cluster as they might move to be more centralized. If cluster members treat the vip as authoritative it doesn't matter how far out it gets (eg in this case) there will still be relative consistency (they all agree on one time, even if a bit off)
