### ISSUE TITLE
Icehouse nova-api worker settings, nova aggregate filters, and nova debug

### ISSUE THREAD

**Issue by bcpc** [bloomberg/chef-bcpc#528]
Set the following in nova.conf

On icehouse, nova-api will spawn a thread for each cpu on the hypervisor.  To limit number of cpus to 2, set the following:
ec2_workers=2
osapi_compute_workers=2
metadata_workers=2
workers=2

For host aggregates to function set the following:
scheduler_default_filters=AggregateInstanceExtraSpecsFilter,AvailabilityZoneFilter,RamFilter,ComputeFilter,DifferentHostFilter,SameHostFilter

Turn on Nova debug:
debug=True

**Comment by kamidzi** [comment]
Why has this issue been opened by @bcpc?

**Comment by kelvk** [comment]
Resolved by #595, #559 and #537.
