### ISSUE TITLE
Switch default Canonical OpenStack repository from "proposed" to "updates"

### ISSUE THREAD

**Issue by kelvk** [bloomberg/chef-bcpc#539]
https://github.com/bloomberg/chef-bcpc/blob/master/cookbooks/bcpc/attributes/default.rb#L11-L12

We should be pulling packages from "updates".

https://wiki.ubuntu.com/StableReleaseUpdates

**Comment by kkoh61** [comment]
We could probably start doing this on Trusty. Thoughts, @erhudy @caiush ?

**Comment by erhudy** [comment]
I actually switched the build over to updates on Trusty already after building the first non-virtualized test cluster. I am totally fine with it.

**Comment by kkoh61** [comment]
Great, thanks.

**Comment by kamidzi** [comment]
What's the status of this?

**Comment by erhudy** [comment]
Icehouse changed from proposed over to updates. Kilo is currently off proposed because when I was doing the work to move BCPC to Kilo originally, the GA release had not been moved to updates. If the GA packages are in trusty-updates now, we can set it back and close this one out.

**Comment by kamidzi** [comment]
This is no longer an issue, no?

**Comment by erhudy** [comment]
We're still using trusty-proposed for Kilo at the moment. I haven't tested trusty-updates since the early days of the Kilo work.

**Comment by erhudy** [comment]
Closing this because we will probably always use proposed so that master builds get the latest and greatest and our actual clusters will continue to build from our tested frozen mirrors.
