### ISSUE TITLE
Fix calculation of default pgs_per_node

### ISSUE THREAD

**Issue by jerenkrantz** [bloomberg/chef-bcpc#549]
In `cookbooks/bcpc/default/attributes.rb`, we set the pgs_per_node to 1024:
```
default['bcpc']['ceph']['pgs_per_node'] = 1024
```

However, ceph enforces a limit of 32 pgs per OSDs:

```
$ ceph osd pool set images pg_num 4096
STDERR: Error E2BIG: specified pg_num 4096 is too large (creating 3584 new PGs on ~12 OSDs exceeds per-OSD max of 32)
```

We can probably (and should) derive the default pgs_per_node setting.  In this case (3 VMs with 4 OSDs each), we can only support 384 placement groups.

(I hit this through a variety of combinations of steps that are reasonable, but not perhaps the default case.  So, I'll elide them here for now.)

**Comment by erhudy** [comment]
I hit this same problem standing up Trusty nodes down in the lab, so +1.

**Comment by pchandra** [comment]
Ok, that's really bizarre since for years, the Inktank docs (and the folks we've talked with) always recommended ~100 per OSD and also with 2-3 times that not being a big problem. Did something change upstream or did this PG count get redefined or something?

**Comment by singn** [comment]
Is there any fix or config change suggested to overcome this issue? I am hitting it everytime I spawn a test cluster with less osds.
Error E2BIG: specified pg_num 1024 is too large (creating 768 new PGs on ~8 OSDs exceeds per-OSD max of 32)

**Comment by erhudy** [comment]
How many OSDs are you creating the cluster with? Your error message says 8, which is how many OSDs are set up in the default configuration.

**Comment by mihalis68** [comment]
If nobody is already working on this I'll take this one

**Comment by erhudy** [comment]
I've purposely avoided it because it works in all our configurations and the math for calculating the PGs is a little opaque and not modified lightly.

**Comment by cloudm2** [comment]
I changed it completely for object store. Just FYI

Thanks

----- Original Message -----
From: Edmund Rhudy <reply@reply.github.com>
To: chef-bcpc@noreply.github.com
At: 11-Apr-2016 13:21:33


I've purposely avoided it because it works in all our configurations and the math for calculating the PGs is a little opaque and not modified lightly.

**Comment by cloudm2** [comment]
The PG max is 300 per OSD. The issue in this case is the 'optimal pg count' going to the next higher power of 2 instead of the nearest power of 2. I will change it.

**Comment by erhudy** [comment]
Do you think the default value of *bcpc.ceph.pgs_per_node* should also be changed? 1024 may be too high a default.

**Comment by cloudm2** [comment]
Yes. In BCS I changed it to 128 as a baseline default

**Comment by erhudy** [comment]
Changed in #1043.
