### ISSUE TITLE
Consider upping default nova-conductor workers from 2 to 5

### ISSUE THREAD

**Issue by jerenkrantz** [bloomberg/chef-bcpc#572]
In testing locally with 1 head node and 2 worker nodes, `nova-conductor` could not keep up with the number of incoming messages with the default value of workers (currently 2).  Upping it to 5 helped dramatically.

```
default['bcpc']['nova']['workers'] = 5
```

(If we agree, I can submit a PR or someone can just push a fix.)

**Comment by erhudy** [comment]
This seems related to #574, confirm? More workers doesn't seem problematic to me in any event, but there may be other shenanigans at work that are causing `nova-conductor` to perform poorly.

**Comment by jerenkrantz** [comment]
Yes, when #574 was also occurring, chaos was ensuing.  However, even after disabling durable queues and resetting everything (so no errors in the logs), two `nova-conductor` threads still couldn't keep up with the load of events coming in (likely due to all of the service check-ins).  An easy way to see this in action is to look at the RabbitMQ dashboard and see the events in the `conductor` queue piling up.

**Comment by erhudy** [comment]
Filed #575 to fix thix.
