### ISSUE TITLE
Make nova-service-restart-wrapper a tunable option

### ISSUE THREAD

**Issue by jerenkrantz** [bloomberg/chef-bcpc#578]
In debugging clusters, having `nova-service-restart-wrapper` run every five minutes is *really* annoying.  We should have a tunable to enable or disable it.

I'd recommend leaving it off - but, at the very least, we need an easy way to skip it.

(My general philosophy is to try to fix the underlying issues rather than applying crude sledgehammers.)

**Comment by caiush** [comment]
Just kill it. It was a patch with the earlier versions of Openstack. It should no longer be required. If it is .. I will be very sad

**Comment by erhudy** [comment]
I will remove it tomorrow.
