### ISSUE TITLE
S3 multipart uploads over radosgw broken in 5.x

### ISSUE THREAD

**Issue by jerenkrantz** [bloomberg/chef-bcpc#596]
With 5.x, I am seeing timeout failures in multipart uploads against `radosgw` over S3 via boto.

`radosgw` does not seem to be responding to the initial request to initiate the multipart upload.  An HTTP request like:

```
POST /bosh-blobstore/concourse-0.50.0.tgz?uploads HTTP/1.1
Host: 192.168.100.5
Accept-Encoding: identity
Date: Fri, 22 May 2015 14:40:30 GMT
Content-Length: 0
Authorization: AWS 2U0B5RZU86DTQGBKTDC1:I+pxTghji29oWtpjHma84I2whFE=
User-Agent: Boto/2.8.0 (darwin)

```

times out with a 500 error.

It should respond with an XML response container of InitiatedMultipartUploadsResult per http://ceph.com/docs/v0.80.5/radosgw/s3/objectops/#initiate-multi-part-upload

The s3put.py from boto needs some hacks to reproduce it.  If it is hard for others to reproduce, I can post a cleaned up version of my s3put.py somewhere.

(FWIW, I first triggered this via setting BOSH to use an S3 endpoint.)

**Comment by erhudy** [comment]
Can you provide your test case that so that I can reproduce the error?

**Comment by jerenkrantz** [comment]
The easiest way is likely to issue `nc` with the HTTP request above - substituting in an existing bucket and credential).

My hacked up version of `s3put.py` from boto is up at https://gist.github.com/jerenkrantz/802971ef79132df7a882 - invoke it with:

```
./s3put.py -d 10 -a <access> -s <secret> -b <bucket-name> --host 192.168.100.5 --port 80 --insecure --ordinary_calling --multipart concourse-0.50.0.tgz
```

To use multipart, it also requires `FileChunkIO` PIP.  Any file bigger than 5MB will invoke the multipart functionality.

If it wasn't clear, non-multipart uploads work just fine.

**Comment by erhudy** [comment]
Was able to reproduce; uploading a Cirros image without multipart worked fine, but enabling it caused the 500s as stated above.

Output from Apache logs when things are failing:
```
[Fri May 22 15:03:57.794613 2015] [fastcgi:error] [pid 12305] [client 192.168.100.5:25555] FastCGI: comm with server "/var/www/s3gw.fcgi" aborted: idle timeout (60 sec)
[Fri May 22 15:03:57.794700 2015] [fastcgi:error] [pid 12305] [client 192.168.100.5:25555] FastCGI: incomplete headers (0 bytes) received from server "/var/www/s3gw.fcgi"
```

**Comment by erhudy** [comment]
RADOSgw debug logging never shows the HTTP 500 errors, so it seems reasonable to suspect FastCGI as the failing component. I will try switching out the existing setup for one using Civetweb and mod_proxy instead and see if it gets any happier.

**Comment by erhudy** [comment]
Switched over to Civetweb and attempted to upload a file directly to the Civetweb port, without Apache or anything else in the way. As before, it worked fine without multipart, but multipart uploads are still failing. It is not returning 500, it just appears to be continually attempting to begin the upload without success. Maybe RADOSgw itself is at fault after all? The RADOSgw debug log does not show it crashing or have any immediately obvious error messages. Continuing to dig.

**Comment by erhudy** [comment]
Worked it out with @caiush; RADOSgw was creating a pool (`.rgw.buckets.extra`) that wasn't in our list of pre-created pools, and this pool was being created with invalid crush ruleset and size parameters. Once that was fixed, I was able to push multipart uploads successfully. Apparently the non-multipart upload mechanism does not require this pool, but multipart does. Will PR the fix shortly.

**Comment by erhudy** [comment]
PR #604 created to fix this issue.

**Comment by jerenkrantz** [comment]
Yup, all happy now once `.rgw.buckets.extra` created.  Thanks!
