### ISSUE TITLE
Investigate switching from mod_fcgi to civetweb for RADOSgw

### ISSUE THREAD

**Issue by erhudy** [bloomberg/chef-bcpc#600]
We currently use mod_fcgi. This issue is for looking at civetweb as a possible replacement for RADOSgw. (See issue #596 as a reason for looking into this.)

**Comment by erhudy** [comment]
One note: it will still need to be fronted by Apache or HAProxy in order to provide SSL termination.

**Comment by jerenkrantz** [comment]
FYI, the latest Ceph radosgw docs recommend `mod_proxy_fcgi` which is way better than `mod_fcgi`.  So, that may also be an alternative.  See http://ceph.com/docs/master/install/install-ceph-gateway/

**Comment by erhudy** [comment]
As part of the Hammer upgrade, @cloudm2 has made this a switchable thing.
