### ISSUE TITLE
Parallel knife bootstraps of work nodes fails in ceph recipe

### ISSUE THREAD

**Issue by kamidzi** [bloomberg/chef-bcpc#610]
Attempting to run knife bootstrap on both work nodes in parallel is causing following failure:
```
10.0.100.13 [2015-05-26T10:35:30-04:00] ERROR: bash[update-rgw-buckets-pg_num] (bcpc::ceph-rgw line 87) had an error: Mixlib::ShellOut::ShellCommandFailed: Expected process to ex
it with [0], but received '16'
10.0.100.13 ---- Begin output of "bash"  "/tmp/chef-script20150526-1098-3yqooh" ----
10.0.100.13 STDOUT:
10.0.100.13 STDERR: Error EBUSY: currently creating pgs, wait
10.0.100.13 ---- End output of "bash"  "/tmp/chef-script20150526-1098-3yqooh" ----
10.0.100.13 Ran "bash"  "/tmp/chef-script20150526-1098-3yqooh" returned 16
10.0.100.13 [2015-05-26T10:35:30-04:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)
```

In the case of two work nodes, one will succeed.

**Comment by erhudy** [comment]
After a little experimentation, if any one node is in the `wait-for-pgs-creating` resource, any other nodes that hit that resource will bail out (and maybe other bad things are happening as well that aren't made obvious by commands failing).

**Comment by erhudy** [comment]
Probably this is actually a resource running before there, like if two nodes are trying to update the Ceph crush map simultaneously (just a guess).
