### ISSUE TITLE
Error thrown by keystone recipe

### ISSUE THREAD

**Issue by kelvk** [bloomberg/chef-bcpc#619]
Thrown during the first chef run, but the head node eventually converges during the second chef-run in https://github.com/bloomberg/chef-bcpc/blob/master/wait_and_bootstrap.sh#L29-L30

10.0.100.11 Recipe: bcpc::keystone
10.0.100.11   * ruby_block[keystone-database-creation] action run
10.0.100.11     - execute the ruby block keystone-database-creation
10.0.100.11   * bash[keystone-database-sync] action run
10.0.100.11     - execute "bash"  "/tmp/chef-script20150602-1099-hol97l"
10.0.100.11 Recipe: bcpc::apache2
10.0.100.11   * service[apache2] action restart
10.0.100.11     - restart service service[apache2]
10.0.100.11 Recipe: bcpc::keystone
10.0.100.11   * bash[keystone-database-sync] action nothing (skipped due to action :nothing)
10.0.100.11   * bash[wait-for-keystone-to-become-operational] action run
10.0.100.11
10.0.100.11     ================================================================================
10.0.100.11     Error executing action `run` on resource 'bash[wait-for-keystone-to-become-operational]'
10.0.100.11     ================================================================================
10.0.100.11
10.0.100.11     Mixlib::ShellOut::CommandTimeout   
10.0.100.11     --------------------------------   
10.0.100.11     Command timed out after 30s:
10.0.100.11     Command exceeded allowed execution time, process terminated
10.0.100.11     ---- Begin output of "bash"  "/tmp/chef-script20150602-1099-wt70c6" ----
10.0.100.11     STDOUT:
10.0.100.11     STDERR:
10.0.100.11     ---- End output of "bash"  "/tmp/chef-script20150602-1099-wt70c6" ----
10.0.100.11     Ran "bash"  "/tmp/chef-script20150602-1099-wt70c6" returned
10.0.100.11
10.0.100.11     Resource Declaration:
10.0.100.11     ---------------------
10.0.100.11     # In /var/chef/cache/cookbooks/bcpc/recipes/keystone.rb
10.0.100.11
10.0.100.11     154: bash "wait-for-keystone-to-become-operational" do
10.0.100.11     155:   code ". /root/keystonerc; until keystone user-list >/dev/null 2>&1; do sleep 1; done"
10.0.100.11     156:   timeout 30
10.0.100.11     157: end
10.0.100.11     158:
10.0.100.11     159: bash "keystone-create-users-tenants" do
10.0.100.11     160:     user "root"
10.0.100.11     161:     code <<-EOH
10.0.100.11     162:         . /root/adminrc
10.0.100.11     163:         . /root/keystonerc
10.0.100.11     164:         export KEYSTONE_ADMIN_TENANT_ID=`keystone tenant-create --name "#{node['bcpc']['admin_tenant']}" --description "Admin services" | grep " id " | awk '{print $4}'`
10.0.100.11     165:         export KEYSTONE_ROLE_ADMIN_ID=`keystone role-create --name "#{node['bcpc']['admin_role']}" | grep " id " | awk '{print $4}'`
10.0.100.11     166:         export KEYSTONE_ADMIN_LOGIN_ID=`keystone user-create --name "$OS_USERNAME" --tenant_id $KEYSTONE_ADMIN_TENANT_ID --pass "$OS_PASSWORD" --email "#{node['bcpc']['admin_email']}" --enabled true | grep " id " | awk '{print $4}'`
10.0.100.11     167:         keystone user-role-add --user_id $KEYSTONE_ADMIN_LOGIN_ID --role_id $KEYSTONE_ROLE_ADMIN_ID --tenant_id $KEYSTONE_ADMIN_TENANT_ID
10.0.100.11     168:     EOH
10.0.100.11     169:     only_if ". /root/keystonerc; . /root/adminrc; keystone user-get $OS_USERNAME 2>&1 | grep -e '^No user'"
10.0.100.11     170: end
10.0.100.11     171: 
10.0.100.11     172: 
10.0.100.11     173: ruby_block "initialize-keystone-test-config" do
10.0.100.11     174:     block do
10.0.100.11     175:         make_config('keystone-test-user', "tester")
10.0.100.11     176:         make_config('keystone-test-password', secure_password)
10.0.100.11     177:     end
10.0.100.11     178: end
10.0.100.11     179: 
10.0.100.11     180: ruby_block "keystone-create-test-tenants" do
10.0.100.11     181:     block do
10.0.100.11     182:         %x[ . /root/adminrc
10.0.100.11     183:             export KEYSTONE_ADMIN_TENANT_ID=`keystone tenant-get "#{node['bcpc']['admin_tenant']}" | grep " id " | awk '{print $4}'`
10.0.100.11     184:             keystone user-create --name #{get_config('keystone-test-user')} --tenant-id $KEYSTONE_ADMIN_TENANT_ID --pass  #{get_config('keystone-test-password')} --enabled true
10.0.100.11     185:         ]
10.0.100.11     186:     end
10.0.100.11     187:     only_if { system ". /root/keystonerc; . /root/adminrc; keystone user-get #{get_config('keystone-test-user')} 2>&1 | grep -e '^No user' >/dev/null" }
10.0.100.11     188: end
10.0.100.11     189: 
10.0.100.11     190: ruby_block "keystone-add-test-admin-role" do
10.0.100.11     191:     block do
10.0.100.11     192:         %x[ . /root/adminrc
10.0.100.11     193:             keystone user-role-add --user #{get_config('keystone-test-user')} --role '#{node['bcpc']['admin_role']}' --tenant '#{node['bcpc']['admin_tenant']}'
10.0.100.11     194:         ]
10.0.100.11     195:     end
10.0.100.11     196:     not_if { system ". /root/keystonerc; . /root/adminrc; keystone user-role-list --user #{get_config('keystone-test-user')} --tenant '#{node['bcpc']['admin_tenant']}' 2>&1 | grep '#{node['bcpc']['admin_role']}' >/dev/null" }
10.0.100.11     197: end
10.0.100.11     Compiled Resource:
10.0.100.11     ------------------
10.0.100.11     # Declared in /var/chef/cache/cookbooks/bcpc/recipes/keystone.rb:154:in `from_file'
10.0.100.11     
10.0.100.11     bash("wait-for-keystone-to-become-operational") do
10.0.100.11       action "run"
10.0.100.11       retries 0
10.0.100.11       retry_delay 2
10.0.100.11       default_guard_interpreter :default
10.0.100.11       command "wait-for-keystone-to-become-operational"
10.0.100.11       backup 5
10.0.100.11       returns 0
10.0.100.11       timeout 30
10.0.100.11       code ". /root/keystonerc; until keystone user-list >/dev/null 2>&1; do sleep 1; done"
10.0.100.11       interpreter "bash"
10.0.100.11       declared_type :bash
10.0.100.11       cookbook_name "bcpc"
10.0.100.11       recipe_name "keystone"
10.0.100.11     end
10.0.100.11
10.0.100.11 Recipe: bcpc::cpupower
10.0.100.11   * service[cpufrequtils] action restart
10.0.100.11     - restart service service[cpufrequtils]

**Comment by kamidzi** [comment]
I can confirm that I have hit this in the past, though I cannot reproduce reliably.

**Comment by erhudy** [comment]
We can try the easy solution first, which is to increase the timeout from 30 seconds up to 60 or 120. It may be that it takes just longer than 30 seconds to become ready. Alternatively, it may be that it just doesn't become ready at all until something executes on the second Chef run, in which case there's some debugging to be done.

**Comment by kelvk** [comment]
This should be fixed by #645.
