### ISSUE TITLE
MySQL Cluster fails to add multiple nodes if wsrep_cluster_name exceeds certain length

### ISSUE THREAD

**Issue by erhudy** [bloomberg/chef-bcpc#649]
I randomly found this while testing a PR today: if `wsrep_cluster_name` exceeds some length (I think greater than 32 characters), the first node will start up fine, but nodes that try to join the cluster will fail and bail out with an error message like `WSREP: handling gmcast protocol message failed: : 90 (Message too long)`. We should add some sort of guard in to cut the environment name down to a max length so that this won't happen (probably not just truncating the environment name, but doing some intelligent like taking capitalized letters or something like that).

**Comment by dionash** [comment]
Unbelievable, but it works.
