### ISSUE TITLE
Too many PGs per OSD

### ISSUE THREAD

**Issue by kelvk** [bloomberg/chef-bcpc#650]
Built off latest master this afternoon:

`vagrant@bcpc-vm1:~$ sudo ceph health detail`
`HEALTH_WARN too many PGs per OSD (816 > max 300)`
`too many PGs per OSD (816 > max 300)`

**Comment by cloudm2** [comment]
This is normal for small builds unless we manually changed the pg count or change the min_xxxx pg setting in ceph.conf.

**Comment by mihalis68** [comment]
This is not normal for chef-bcpc, previously we have always been able to get to HEALTH_OK on a small cluster. I have multiple scripts that look for that. I don't want to lose that else we will start ignoring HEALTH_WARN.

**Comment by mihalis68** [comment]
Ok so to clarify, I've been told this condition is not new, but the warning is. Well, I don't want warning by default every time I build, so I have assigned this to myself.

**Comment by cloudm2** [comment]
The Calc with min for certain size cluster or setting the min warning flag off in Ceph.conf. This is a common issue on the irc channels. Hope it makes sense, I'm doing this from my phone :)

**Comment by mihalis68** [comment]
I will probably just try increasing the number of OSDs per VM so that this warning goes away, leaving the check live in case we misconfigure a real on-metal cluster.

**Comment by erhudy** [comment]
This can be hackerated around via #780, though I'm pretty sure pretty sure @caiush wants to revisit how the calculation is done anyway.

**Comment by erhudy** [comment]
This is fixed now that #1043 has been merged, which reduced the default PGs per node to 128. This can still be increased at will.
