### ISSUE TITLE
Guests booted from image are not using RBD-backed disk

### ISSUE THREAD

**Issue by kelvk** [bloomberg/chef-bcpc#651]
The disk should be backed by RBD in the "vms" pool. nova.conf needs to be updated to reflect Kilo configuration changes per http://ceph.com/docs/master/rbd/rbd-openstack/.

We should also verify Glance and Cinder configurations.

**Comment by cloudm2** [comment]
Changes are being made in the ephemeral pull request to reflect juno/kilo style formatting that I will be issuing when I get back.

**Comment by mihalis68** [comment]
What is a test to verify that with this patch in the behavior is now correct? I have a cluster built with it but not sure how to verify.

**Comment by kelvk** [comment]
Spin up an instance (boot from image) and log onto its hypervisor. In /var/lib/nova/instances/<instance uuid>/libvirt.xml, you should see something like:

`<disk type="network" device="disk">`
      `<driver type="raw" cache="writeback"/>`
      `<source protocol="rbd" name="vms/<instance uuid>_disk">`

**Comment by mihalis68** [comment]
Confirming this works for me. I merged it by hand and built using vagrant. Then I made a Cirros image which landed on bcpc-vm1. In that machine, the XML looks like this:

```
<devices>
    <disk type="network" device="disk">
      <driver type="raw" cache="writeback"/>
      <source protocol="rbd" name="vms/a4f55d7c-1e8e-437e-a75a-20c923ed88be_disk">
        <host name="172.16.100.11" port="6789"/>
      </source>
      <auth username="admin">
        <secret type="ceph" uuid="07d6ad79-8da9-4fda-a758-3fecb75dabfa"/>
      </auth>

```
