### ISSUE TITLE
BCPC nodes can lose default route in table main

### ISSUE THREAD

**Issue by mihalis68** [bloomberg/chef-bcpc#654]
We have previous seen nodes lose default routes for the storage and mgmt networks (which use named routing tables of the same name. This causes bizarre and mysterious issues with the node. The routemon service handles those failures. Now I have recently seen a couple of real (non-virtual) nodes lose the default route on the default NIC (typically eth0) described in routing table 'main'.  That can cause failure to hit external services such as DNS and NTP servers.

We should monitor and fix that situation in a similar way.

**Comment by mihalis68** [comment]
From @pchandra come the suggestions to use something like this:

```
In terms of treating the symptoms, we could add a line like the following to bcpc-routing to address this:

ip route add default via <%=@node["bcpc"]["floating"]["gateway"]%> \
         dev <%=@node["bcpc"]["floating"]["interface"]%> \
         table main

But that might lead to multiple default route lines in table main if it keeps adding repeats every time it runs.... So might need to preceed it with something like:

ip route del default dev <%=@node["bcpc"]["floating"]["interface"]%> \
         table main
```

**Comment by erhudy** [comment]
Was this resolved with your changes to routemon.pl?

**Comment by mihalis68** [comment]
Yes I believe all problems of losing the default routes have been fixed and actually routemon is no longer needed
