### ISSUE TITLE
ceph auth squawks with Hammer

### ISSUE THREAD

**Issue by mihalis68** [bloomberg/chef-bcpc#699]
unprivileged users on hypervisors issuing ceph commands get :
```
2015-07-13 17:01:58.901246 7fc1f91eb700 -1 asok(0x7fc1f0000bf0) AdminSocketConfigObs::init: failed:
 AdminSocket::bind_and_listen: failed to bind the UNIX domain socket to '/var/run/ceph/ceph-
client.admin.14974.140470931950816.asok': (13) Permission denied
```

**Comment by mihalis68** [comment]
doing
```
sudo chmod 777 /var/run/ceph
```
Stops the squawking, as per http://tracker.ceph.com/issues/5972 but I don't know if that is acceptable.

**Comment by cloudm2** [comment]
We need to look back to see if removing the ceph mds section had a permission setting in it or ceph auth add or something.

**Comment by mihalis68** [comment]
Duplicate of https://github.com/bloomberg/chef-bcpc/issues/652
