### ISSUE TITLE
VM's don't know their tenancy is part of their DNS name

### ISSUE THREAD

**Issue by cbaenziger** [bloomberg/chef-bcpc#77]
After 7210d70ca78d21950bf6740b4fd33c736612f87b, the VMs nolonger know their proper DNS name.

The metadata server returns the <vm name>.<domain> via http://169.254.169.254/latest/meta-data/public-hostname. Also, stock Ubuntu VM image's end up setting the VM's FQDN to <vm name>.<domain> (also missing the tenancy name in the actual FQDN).

**Comment by erhudy** [comment]
Closing because DNS has been completely redone for 5.x.
