### ISSUE TITLE
Ceph log rotation breaks radosgw logging

### ISSUE THREAD

**Issue by kelvk** [bloomberg/chef-bcpc#772]
There are two log rotation scripts, `/etc/logrotate.d/ceph` and `/etc/logrotate.d/radosgw`, but only the former comes into effect because radosgw for unknown reason, does not log to `/var/log/radosgw`. When ceph log rotation runs, it greedily rotates `/var/log/ceph/radosgw.log` as well. Since this is unintended, the radosgw daemon never received a HUP signal to release the log.

When log is broken:
<pre>
radosgw 47936 root    3w   REG                8,5  4558962 15212973 /var/log/ceph/radosgw.log.1 (deleted)
</pre>

After HUP-ing it:
<pre>
radosgw 47936 root    3w   REG                8,5     2688 15213286 /var/log/ceph/radosgw.log
</pre>

This is particularly an issue because the log file is monitored by Zabbix.

**Comment by cloudm2** [comment]
I believe originally when I came on, I saw that we moved rgw logging to the apache logging. Now that we have moved to civetweb well... :)

**Comment by erhudy** [comment]
It looks like nothing is being written to `radosgw.log` anyway, so the condition Zabbix is checking for won't be met regardless (specifically, `grep -B 1 '"GET / HTTP/1.0"' | grep http_status=200 | wc -l` against the log file).
