### ISSUE TITLE
Set min_size when increasing size on Ceph pools

### ISSUE THREAD

**Issue by erhudy** [bloomberg/chef-bcpc#788]
At present we fail to set `min_size` appropriately when increasing the value of `size`. This is easy to adjust manually, but we should have it set a more sensible default for `min_size` as well.

Using _(n/2)+1_ where _n_ is `size` is one candidate, which would give the following results up to 5:
- size 1, min_size 1
- size 2, min_size 2
- size 3, min_size 2
- size 4, min_size 3
- size 5, min_size 3

Another candidate is _(n.to_f/2).ceil_, which would give the following results up to 5:
- size 1, min_size 1
- size 2, min_size 1
- size 3, min_size 2
- size 4, min_size 2
- size 5, min_size 3

**Comment by kamidzi** [comment]
From  @erhudy, offline:
```
ceph osd pool ls | xargs -I% ceph osd pool set % min_size 2`
```
