### ISSUE TITLE
getty processes crash repeatedly in virtualized local builds

### ISSUE THREAD

**Issue by erhudy** [bloomberg/chef-bcpc#791]
With the merge of #735, when building locally, the `ttyS0` and `ttyS1` processes repeatedly crash and are respawned by Upstart:
```
Aug 25 13:43:05 vagrant-ubuntu-trusty-64 kernel: [  662.010796] init: ttyS0 main process (14186) terminated with status 1
Aug 25 13:43:05 vagrant-ubuntu-trusty-64 kernel: [  662.010808] init: ttyS0 main process ended, respawning
Aug 25 13:43:05 vagrant-ubuntu-trusty-64 kernel: [  662.054730] init: ttyS1 main process (14194) terminated with status 1
Aug 25 13:43:05 vagrant-ubuntu-trusty-64 kernel: [  662.054749] init: ttyS1 main process ended, respawning
```
This doesn't appear to occur on hardware.

**Comment by kamidzi** [comment]
Confirm. Only started seeing this yesterday.

**Comment by erhudy** [comment]
After stracing the processes on the VM versus a hardware system, it looks like this is getty's reaction to the serial port not actually existing (you can reproduce on hardware as well by trying to set up a getty on ttyS2 and beyond). I made it happy again by adding fake serial ports to the VMs that don't go anywhere:
```
➜  vagrant_scripts git:(master) VBoxManage modifyvm bcpc-vm3 --uart1 0x3F8 4    
➜  vagrant_scripts git:(master) VBoxManage modifyvm bcpc-vm3 --uart2 0x2F8 3
➜  vagrant_scripts git:(master) VBoxManage modifyvm bcpc-vm3 --uartmode1 disconnected
➜  vagrant_scripts git:(master) VBoxManage modifyvm bcpc-vm3 --uartmode2 disconnected
```
I will work this into a PR to modify the Vagrantfile so that these serial ports are added to each VM.
