### ISSUE TITLE
Change default cinder volumes FROM 10 TO -1

### ISSUE THREAD

**Issue by dkaplan34** [bloomberg/chef-bcpc#797]
Change default cinder volumes FROM 10 TO -1
@@ -987,7 +987,7 @@ default['bcpc']['nova']['policy'] = {
 default['bcpc']['cinder']['verbose'] = false
 default['bcpc']['cinder']['workers'] = 5
 default['bcpc']['cinder']['quota'] = {
-  "volumes" => 10,
+  "volumes" => -1,
   "quota_snapshots" => 10,
   "consistencygroups" => 10,
   "gigabytes" => 1000

**Comment by dkaplan34** [comment]
full change
--- a/cookbooks/bcpc/attributes/default.rb
+++ b/cookbooks/bcpc/attributes/default.rb
@@ -987,7 +987,7 @@ default['bcpc']['nova']['policy'] = {
 default['bcpc']['cinder']['verbose'] = false
 default['bcpc']['cinder']['workers'] = 5
 default['bcpc']['cinder']['quota'] = {
-  "volumes" => 10,
+  "volumes" => -1,
   "quota_snapshots" => 10,
   "consistencygroups" => 10,
   "gigabytes" => 1000

**Comment by erhudy** [comment]
Resolved by merging #805.
