### ISSUE TITLE
Increase RabbitMQ traffic distribution during normal circumstances

### ISSUE THREAD

**Issue by kelvk** [bloomberg/chef-bcpc#811]
On a deployed cluster, one of the headnodes is the preferred RabbitMQ node on 2/3 headnodes. We perhaps could make the local RabbitMQ instance as preferred and randomize rest of the list.

**Comment by erhudy** [comment]
The function that does the shuffle is only used by the RabbitMQ template, I think, so it should be pretty straightforward to have it reorder the list to put the IP address of the system it's running on at the head of the list.

**Comment by kelvk** [comment]
Implemented by #930
