### ISSUE TITLE
Consider changing boot from image/volume terminology in Horizon

### ISSUE THREAD

**Issue by erhudy** [bloomberg/chef-bcpc#833]
User feedback indicates that terminology like **Boot from image** is confusing and does not adequately convey the differences in the choices.

Proposed changes to the terminology in Horizon:
* **Boot from image** ➜ **Clone image to new temporary root volume**
* **Boot from snapshot** ➜ **Boot from image snapshot** (users are disabled from choosing this anyway, but might as well clarify it versus volume)
* **Boot from volume** ➜ **Boot from existing persistent root volume**
* **Boot from image (creates a new volume)** ➜ **Clone image to new persistent root volume**
* **Boot from volume snapshot (creates a new volume)** ➜ **Clone volume snapshot to new persistent root volume**

These are a little verbose, maybe necessarily so but maybe not, so suggestions on improvements are welcome.

**Comment by kamidzi** [comment]
I'm not this will actually dispell confusion as intended. A separate help section may be a more sustainable approach; I actually think the upstream has a reasonable solution in the forthcoming release: https://github.com/openstack/horizon/blob/stable/liberty/openstack_dashboard/dashboards/project/static/dashboard/project/workflow/launch-instance/source/source.help.html
