### ISSUE TITLE
haproxy.cfg for monitoring re-generated on each Chef run

### ISSUE THREAD

**Issue by kelvk** [bloomberg/chef-bcpc#840]
The configuration file is changed on each Chef run, resulting in restart of haproxy. We may need to persist the password string (https://github.com/bloomberg/chef-bcpc/blob/master/cookbooks/bcpc/templates/default/haproxy-monitoring.cfg.erb#L35) in the data bag.

**Comment by kamidzi** [comment]
Good catch! Looks like it's because the salt is being regenerated. The hash should be constant given a constant salt.
