### ISSUE TITLE
Diamond CloudCollector should be disabled on monitoring cluster

### ISSUE THREAD

**Issue by kelvk** [bloomberg/chef-bcpc#896]
On a monitoring cluster:

`[2015-11-05T16:46:03+00:00] ERROR: template[/etc/diamond/collectors/CloudCollector.conf] (bcpc::diamond line 133) had an error: RuntimeError: No config found for get_config(mysql-root-user)!!!`

**Comment by kamidzi** [comment]
Btw, for record's sake: this is because in actual hardware deployments, monitoring clusters do not have `BCPC-Headnode`s, hence no `mysql-head` recipe -> no config created for `mysql-root-{user,password}`
