### ISSUE TITLE
routemon no longer needed

### ISSUE THREAD

**Issue by mihalis68** [bloomberg/chef-bcpc#908]
The routemon service in chef-bcpc tries to spot and fix default routes going away from the various bcpc routing tables. This was necessary when we were not correctly marking such routes as static, however due to https://github.com/bloomberg/chef-bcpc/pull/718 that is now fixed. Remove the routemon stuff entirely on new cluster builds.

**Comment by kamidzi** [comment]
Closed via 24496b5
