### ISSUE TITLE
Ansible playbook synchronize tasks failing with rsync error

### ISSUE THREAD

**Issue by kamidzi** [bloomberg/chef-bcpc#910]
getting
```
msg: bash: sudo rsync: command not found
rsync: connection unexpectedly closed (0 bytes received so far) [sender]
rsync error: remote command not found (code 127) at io.c(226) [sender=3.1.0]
```
Seems like `rsync_path` is getting set to "sudo rsync" by default somehow in something similar to https://github.com/ansible/ansible/issues/7182. Work-around is to set `rsync_path="rsync"`
for synchronize tasks in `bootstrap_deployment/tasks-configure-package-serving.yml`

```
ansible-playbook 1.9.4
  configured module search path = /usr/share/ansible
```

**Comment by erhudy** [comment]
By default all the tasks in this task list are running with sudo because of `become: yes`. Try adding `become: no` to the synchronize tasks and see if that fixes it as well.

**Comment by kamidzi** [comment]
Either seems to work

**Comment by erhudy** [comment]
I'll file a PR to set `become: no` on any synchronize tasks in a little while.
