### ISSUE TITLE
Cobbler recipe does not distinguish between different kernel versions for ubuntu distro

### ISSUE THREAD

**Issue by kamidzi** [bloomberg/chef-bcpc#922]
Right now, whatever may happen to be the latest installer iso is downloaded and imported as *the* ubuntu distro. This will lock the version of the installer kernel whereas the local bootstrap mirror may not contain the supporting modules/packages.

**Comment by erhudy** [comment]
Should be fixed now by #999 (as long as you specify a kernel version).

**Comment by erhudy** [comment]
Remainder is fixed by #1066, allowing you to create arbitrary Cobbler distros and profiles.
