### ISSUE TITLE
DNS Root queries through vip receive no responses

### ISSUE THREAD

**Issue by kamidzi** [bloomberg/chef-bcpc#979]
See #975

**Comment by kelvk** [comment]
Does your VIP holder have connectivity to the [recursing nameserver](https://github.com/bloomberg/chef-bcpc/blob/master/cookbooks/bcpc/templates/default/pdns.conf.erb#L197)?

**Comment by erhudy** [comment]
On our local Vagrant builds, the only network that has access to the outside world is the Vagrant-mandated NAT interface (eth0), which doesn't exist on hardware builds. It's possible that the wackity routing rules are interacting with this interface in some strange way; wouldn't be the first time we've seen strange behavior from those.

**Comment by kamidzi** [comment]
Could not reproduce.
