### ISSUE TITLE
Improve post-crash analysis capabilities

### ISSUE THREAD

**Issue by erhudy** [bloomberg/chef-bcpc#991]
Because real machines sometimes kernel panic, it would be good to be able to collect debugging information on kernel panics instead of screenshotting what's visible of the crash trace off the console.

**Comment by erhudy** [comment]
We also need to improve our ability to collect information on application-level crashes (for example, one we've been seeing lately where nova-compute crashes when interacting with librbd, but we don't get a Python traceback because the crash occurs in FFI and takes out the interpreter).

**Comment by cbaenziger** [comment]
For what it's worth, in Chef-BACH we did bloomberg/chef-bach#377 to help for kernel panics which has served us well.

I look forward to seeing what you do for application crashes; [Apport](https://wiki.ubuntu.com/Apport)?

**Comment by erhudy** [comment]
Apport is what I was planning to install to try to capture application crashes, yeah.

**Comment by erhudy** [comment]
For kernel panics I was planning something similar to your PR. Mostly installing it in the preseed so that additional reboots are not required to enable **crashkernel** is what would be of prime importance.

**Comment by erhudy** [comment]
As a side note, apport causes considerable excitement if a Ceph OSD crashes, propelling system load average to somewhere around 3200 before the crash dump completes.

**Comment by erhudy** [comment]
Rescoping this to just be apport and declaring it done (separate issue opened for crashkernel at #1072).
